/** @type {import('tailwindcss').Config} */
export default {
  content: ['./index.html', './src/**/*.{js,jsx}'],
  darkMode: 'class',
  theme: {
    extend: {
      colors: {
        'bg-stone': '#FAFAF9',
        'text-strong': '#1C1917',
        'text-body': '#44403C',
        'text-muted': '#78716C',
        'border': '#E7E5E4',
        'surface': '#FFFFFF',
        'amber-700': '#B45309',
        'amber-600': '#D97706',
        'amber-50': '#FFFBEB',
        'primary': '#903f00',
        'primary-container': '#b45309',
        'primary-fixed': '#ffdbca',
        'primary-fixed-dim': '#ffb68e',
        'on-primary': '#ffffff',
        'on-primary-fixed': '#331200',
        'on-primary-fixed-variant': '#763300',
        'on-primary-container': '#fff1eb',
        'secondary': '#645d58',
        'secondary-container': '#eae1da',
        'secondary-fixed': '#eae1da',
        'secondary-fixed-dim': '#cec5bf',
        'on-secondary': '#ffffff',
        'on-secondary-container': '#6a635e',
        'on-secondary-fixed': '#1f1b17',
        'on-secondary-fixed-variant': '#4b4641',
        'tertiary': '#005998',
        'tertiary-container': '#0072c0',
        'tertiary-fixed': '#d2e4ff',
        'tertiary-fixed-dim': '#9fcaff',
        'on-tertiary': '#ffffff',
        'on-tertiary-container': '#eef3ff',
        'on-tertiary-fixed': '#001d36',
        'on-tertiary-fixed-variant': '#00497e',
        'background': '#fff8f6',
        'on-background': '#231914',
        'surface-dim': '#ead6cd',
        'surface-bright': '#fff8f6',
        'surface-container-lowest': '#ffffff',
        'surface-container-low': '#fff1eb',
        'surface-container': '#feeae1',
        'surface-container-high': '#f8e4db',
        'surface-container-highest': '#f2dfd6',
        'surface-variant': '#f2dfd6',
        'surface-tint': '#9b4500',
        'on-surface': '#231914',
        'on-surface-variant': '#564338',
        'outline': '#897267',
        'outline-variant': '#ddc1b3',
        'inverse-surface': '#3a2e28',
        'inverse-on-surface': '#ffede5',
        'inverse-primary': '#ffb68e',
        'error': '#ba1a1a',
        'on-error': '#ffffff',
        'error-container': '#ffdad6',
        'on-error-container': '#93000a',
        'success': '#4D7C5F',
        'warning': '#A16207',
        'critical': '#9F3A38',
      },
      borderRadius: {
        DEFAULT: '0.25rem',
        lg: '0.5rem',
        xl: '0.75rem',
        full: '9999px',
      },
      spacing: {
        base: '4px',
        xs: '8px',
        sm: '12px',
        md: '16px',
        lg: '24px',
        xl: '32px',
        '2xl': '48px',
        '3xl': '64px',
        '4xl': '96px',
        'container-max': '1200px',
        'section-v-pad-desktop': '96px',
        'section-v-pad-mobile': '64px',
      },
      fontFamily: {
        'h1-desktop': ['Geist', 'sans-serif'],
        'h1-mobile': ['Geist', 'sans-serif'],
        'h2-desktop': ['Geist', 'sans-serif'],
        'h2-mobile': ['Geist', 'sans-serif'],
        'h3-desktop': ['Geist', 'sans-serif'],
        'h3-mobile': ['Geist', 'sans-serif'],
        'h4': ['Geist', 'sans-serif'],
        'body-lg': ['Geist', 'sans-serif'],
        'body': ['Geist', 'sans-serif'],
        'body-sm': ['Geist', 'sans-serif'],
        'caption': ['Geist', 'sans-serif'],
        'mono-label': ['JetBrains Mono', 'monospace'],
      },
      fontSize: {
        'h1-desktop': ['56px', { lineHeight: '1.1', letterSpacing: '-0.02em', fontWeight: '600' }],
        'h1-mobile': ['36px', { lineHeight: '1.1', letterSpacing: '-0.02em', fontWeight: '600' }],
        'h2-desktop': ['40px', { lineHeight: '1.2', fontWeight: '600' }],
        'h2-mobile': ['28px', { lineHeight: '1.2', fontWeight: '600' }],
        'h3-desktop': ['24px', { lineHeight: '1.3', fontWeight: '600' }],
        'h3-mobile': ['20px', { lineHeight: '1.3', fontWeight: '600' }],
        'h4': ['18px', { lineHeight: '1.4', fontWeight: '600' }],
        'body-lg': ['18px', { lineHeight: '1.6', fontWeight: '400' }],
        'body': ['16px', { lineHeight: '1.6', fontWeight: '400' }],
        'body-sm': ['14px', { lineHeight: '1.5', fontWeight: '400' }],
        'caption': ['13px', { lineHeight: '1.4', fontWeight: '400' }],
        'mono-label': ['14px', { lineHeight: '1.0', fontWeight: '500' }],
      },
    },
  },
  plugins: [require('@tailwindcss/forms')],
}
